# arxivの学問領域の指定
subject: 'cat:cs.CL'

# 検索キーワード
keywords:
        natural language generation: 3
        advertisement: 3
        advertising: 3
        ad text: 4
        search engine advertising: 3
        document understanding: 2
        landing page: 1
        summarization: 4
        query-focused: 4
        purchase funnel: 3
        buying funnel: 3
        marketing funnel: 3
        search intent: 3
        intent classification: 3
        intent: 1
        product title: 2
        query expansion: 1
        clickbait: 1
        survey: 1
        data-to-text: 1
        table-to-text: 1
        hallucination: 1
        hallucinated: 1
        faithfulness: 1
        factuality: 1
        factual: 1
        instruction tuning: 3
        RLHF: 3

# mixture of experts: 2
# multiple choice learning: 2        
# multi choice learning: 2       

# 通知の閾値
score_threshold: 0
