# arxivの学問領域の指定
subject: 'cat:cs.CL'

# 検索キーワード
keywords:
        data-to-text: 5
        Data-to-Text: 5
        table-to-text: 5
        Table-to-Text: 5
        natural language generation: 3
        advertisement: 1
        advertising: 1
        ad text: 1
        search engine advertising: 1
        nested named entity recognition: 1
        document understanding: 3
        landing page: 1
        mixture of experts: 2
        multiple choice learning: 2        
        multi choice learning: 2        

# 通知の閾値
score_threshold: 0
