# arxivの学問領域の指定
subject: 'cat:cs.CL'

# 検索キーワード
keywords:
        data-to-text: 5
        table-to-text: 5
        natural language generation: 3
        advertisement: 1
        advertising: 1

# 通知の閾値
score_threshold: 0
