# arxivの学問領域の指定
subject: 'cat:cs.CL'

# 検索キーワード
keywords:
        advertisement: 3
        advertising: 3
        ad text: 4
        search engine advertising: 3
        document understanding: 2
        landing page: 1
        summarization: 4
        query-focused: 4
        purchase funnel: 3
        buying funnel: 3
        marketing funnel: 3
        search intent: 3
        product title: 2
        clickbait: 1
        preference: 3
        attractiveness: 2

# natural language generation: 3
# instruction tuning: 3
# RLHF: 3
# human preference: 3
# data-to-text: 1
# table-to-text: 1
# survey: 1
# query expansion: 1
# intent classification: 3
# intent: 1
# mixture of experts: 2
# multiple choice learning: 2        
# multi choice learning: 2       

# 通知の閾値
score_threshold: 0
