# arxivの学問領域の指定
subject: 'cat:cs.CL'

# 検索キーワード
keywords:
        data-to-text: 1
        Data-to-Text: 1
        table-to-text: 1
        Table-to-Text: 1
        natural language generation: 3
        advertisement: 1
        advertising: 1
        ad text: 1
        search engine advertising: 1
        document understanding: 2
        hallucination: 3
        hallucinated: 3
        faithfulness: 3
        factuality: 3
        factual: 3
        landing page: 1
        mixture of experts: 2
        multiple choice learning: 2        
        multi choice learning: 2       
        summarization: 4
        query-focused: 4

# 通知の閾値
score_threshold: 0
